import "./globals.css";
import { Inter } from "next/font/google";
import Select from "./select";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Select></Select>
                {children}
            </body>
        </html>
    );
}
